name: 'Push to Docker Hub'
description: 'Push to Docker Hub'

inputs:
  DOCKERHUB_USERNAME:
    description: 'DockerHub username'
    required: true
  DOCKERHUB_TOKEN:
    description: 'DockerHub token'
    required: true
  image-name:
    description: 'Container image name'
    required: true
  image-tag:
    description: 'Container Image Tag'
    required: true  
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: true  
runs:
  using: composite
  steps:
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}
        tags: ${{ inputs.image-tag }}
        registry: docker.io
        dockerfile: ${{ inputs.dockerfile-path }}
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}